baseURL = "https://dry-yard-test-netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Dry Yard Test"
[markup.goldmark.renderer]
unsafe = true
